### ISSUE TITLE
Fix pip install

### ISSUE THREAD

**Issue by agude** [agude/wayback-machine-archiver#8]
```pip install wayback-machine-archiver```

Yields:

```
Collecting wayback-machine-archiver
Could not find a version that satisfies the requirement wayback-machine-archiver (from versions: )
No matching distribution found for wayback-machine-archiver
```

**Comment by agude** [comment]
Full error:

```
Created temporary directory: /tmp/pip-ephem-wheel-cache-xofn1nxq
Created temporary directory: /tmp/pip-req-tracker-vplh60fj
Created requirements tracker '/tmp/pip-req-tracker-vplh60fj'
Created temporary directory: /tmp/pip-install-a3cc4cqm
Collecting wayback_machine_archiver
  1 location(s) to search for versions of wayback-machine-archiver:
  * https://pypi.org/simple/wayback-machine-archiver/
  Getting page https://pypi.org/simple/wayback-machine-archiver/
  Looking up "https://pypi.org/simple/wayback-machine-archiver/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/wayback-machine-archiver/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/wayback-machine-archiver/
    Skipping link https://files.pythonhosted.org/packages/57/ae/6057a510a29e040b37a2c59c9ad10b4e53b24b426d593a03889e15f2a89e/Wayback%20Machine%20Archiver-1.0.0.tar.gz#sha256=bc638c554690807eb50fa203a642a42a76af67f95f49064992f11d02fdc46903 (from https://pypi.org/simple/wayback-machine-archiver/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <4); Missing project version for wayback-machine-archiver
    Skipping link https://files.pythonhosted.org/packages/98/f5/dc295f385dc852a3bc1307d5a01e3f7ad90931771aab5a664bb4b303e097/Wayback%20Machine%20Archiver-1.1.0.tar.gz#sha256=9067446835149bf51fd383c30f5e3cffdca24a3614738e5308bfd00eb44fbb27 (from https://pypi.org/simple/wayback-machine-archiver/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <4); Missing project version for wayback-machine-archiver
  Could not find a version that satisfies the requirement wayback_machine_archiver (from versions: )
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-vplh60fj'
No matching distribution found for wayback_machine_archiver
Exception information:
Traceback (most recent call last):
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/agude/bin/anaconda/lib/python3.7/site-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for wayback_machine_archiver
```

**Comment by agude** [comment]
It was the `name="Wayback Machine Archiver"` in `setup.py`. Spaces are not allowed in the name.
